"""add_organisations_and_tenant_ids

Revision ID: 7a28f92acb7e
Revises: aac23d237e98
Create Date: 2026-07-04 15:26:00.591080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a28f92acb7e'
down_revision: Union[str, Sequence[str], None] = 'aac23d237e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_is_active'), 'organisations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.add_column('alerts', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alerts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_created_by'), 'alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alerts_organisation_id'), 'alerts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_alerts_updated_at'), 'alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_alerts_updated_by'), 'alerts', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'alerts', 'organisations', ['organisation_id'], ['id'])
    op.add_column('customers', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_created_by'), 'customers', ['created_by'], unique=False)
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customers_organisation_id'), 'customers', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_customers_updated_at'), 'customers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_customers_updated_by'), 'customers', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'customers', 'organisations', ['organisation_id'], ['id'])
    op.add_column('devices', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('devices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_created_by'), 'devices', ['created_by'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_devices_organisation_id'), 'devices', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_devices_updated_at'), 'devices', ['updated_at'], unique=False)
    op.create_index(op.f('ix_devices_updated_by'), 'devices', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'devices', 'organisations', ['organisation_id'], ['id'])
    op.add_column('patrols', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('patrols', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('patrols', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('patrols', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_patrols_created_at'), 'patrols', ['created_at'], unique=False)
    op.create_index(op.f('ix_patrols_created_by'), 'patrols', ['created_by'], unique=False)
    op.create_index(op.f('ix_patrols_is_deleted'), 'patrols', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patrols_organisation_id'), 'patrols', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_patrols_updated_at'), 'patrols', ['updated_at'], unique=False)
    op.create_index(op.f('ix_patrols_updated_by'), 'patrols', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'patrols', 'organisations', ['organisation_id'], ['id'])
    op.add_column('users', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'officer'"),
               nullable=True)
    op.drop_column('users', 'organisation_id')
    op.drop_constraint(None, 'patrols', type_='foreignkey')
    op.drop_index(op.f('ix_patrols_updated_by'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_updated_at'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_organisation_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_is_deleted'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_created_by'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_created_at'), table_name='patrols')
    op.alter_column('patrols', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('patrols', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('patrols', 'organisation_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_updated_by'), table_name='devices')
    op.drop_index(op.f('ix_devices_updated_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_organisation_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_by'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.alter_column('devices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('devices', 'organisation_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_updated_by'), table_name='customers')
    op.drop_index(op.f('ix_customers_updated_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_organisation_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('customers', 'organisation_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_updated_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_updated_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organisation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('alerts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('alerts', 'organisation_id')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_is_active'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
