"""initial_enterprise_schema

Revision ID: aac23d237e98
Revises: 
Create Date: 2026-07-04 15:25:24.539799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac23d237e98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alerts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_created_by'), 'alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alerts_updated_at'), 'alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_alerts_updated_by'), 'alerts', ['updated_by'], unique=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_created_by'), 'customers', ['created_by'], unique=False)
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customers_updated_at'), 'customers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_customers_updated_by'), 'customers', ['updated_by'], unique=False)
    op.alter_column('devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('devices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_created_by'), 'devices', ['created_by'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_devices_updated_at'), 'devices', ['updated_at'], unique=False)
    op.create_index(op.f('ix_devices_updated_by'), 'devices', ['updated_by'], unique=False)
    op.alter_column('patrols', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('patrols', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('patrols', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_patrols_created_at'), 'patrols', ['created_at'], unique=False)
    op.create_index(op.f('ix_patrols_created_by'), 'patrols', ['created_by'], unique=False)
    op.create_index(op.f('ix_patrols_is_deleted'), 'patrols', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patrols_updated_at'), 'patrols', ['updated_at'], unique=False)
    op.create_index(op.f('ix_patrols_updated_by'), 'patrols', ['updated_by'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'officer'"),
               nullable=True)
    op.drop_index(op.f('ix_patrols_updated_by'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_updated_at'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_is_deleted'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_created_by'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_created_at'), table_name='patrols')
    op.alter_column('patrols', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('patrols', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patrols', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_devices_updated_by'), table_name='devices')
    op.drop_index(op.f('ix_devices_updated_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_by'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.alter_column('devices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_customers_updated_by'), table_name='customers')
    op.drop_index(op.f('ix_customers_updated_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_alerts_updated_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_updated_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('alerts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
