"""add canonical domain model

Revision ID: c6b03fd24b2a
Revises: e42b7f1a9c30
Create Date: 2026-08-01 20:10:57.791726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b03fd24b2a'
down_revision: Union[str, Sequence[str], None] = 'e42b7f1a9c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('aggregate_root_type', sa.String(), nullable=False),
    sa.Column('aggregate_root_id', sa.Integer(), nullable=False),
    sa.Column('owning_service', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'object_type', 'object_id', name='uq_domain_object_identity')
    )
    op.create_index(op.f('ix_domain_objects_aggregate_root_id'), 'domain_objects', ['aggregate_root_id'], unique=False)
    op.create_index(op.f('ix_domain_objects_aggregate_root_type'), 'domain_objects', ['aggregate_root_type'], unique=False)
    op.create_index(op.f('ix_domain_objects_created_at'), 'domain_objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_objects_object_id'), 'domain_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_domain_objects_object_type'), 'domain_objects', ['object_type'], unique=False)
    op.create_index(op.f('ix_domain_objects_organisation_id'), 'domain_objects', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_domain_objects_retired_at'), 'domain_objects', ['retired_at'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_qualification_code')
    )
    op.create_index(op.f('ix_qualifications_code'), 'qualifications', ['code'], unique=False)
    op.create_index(op.f('ix_qualifications_created_at'), 'qualifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_qualifications_created_by'), 'qualifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_qualifications_is_deleted'), 'qualifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_qualifications_organisation_id'), 'qualifications', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_qualifications_status'), 'qualifications', ['status'], unique=False)
    op.create_index(op.f('ix_qualifications_updated_at'), 'qualifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_qualifications_updated_by'), 'qualifications', ['updated_by'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_identifier', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('employment_role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'employee_identifier', name='uq_employees_org_identifier'),
    sa.UniqueConstraint('user_id', name='uq_employees_user')
    )
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_created_by'), 'employees', ['created_by'], unique=False)
    op.create_index(op.f('ix_employees_employee_identifier'), 'employees', ['employee_identifier'], unique=False)
    op.create_index(op.f('ix_employees_employment_role'), 'employees', ['employment_role'], unique=False)
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employees_organisation_id'), 'employees', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_source_kind'), 'employees', ['source_kind'], unique=False)
    op.create_index(op.f('ix_employees_updated_at'), 'employees', ['updated_at'], unique=False)
    op.create_index(op.f('ix_employees_updated_by'), 'employees', ['updated_by'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('staffing_requirement', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('operational_risk', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'customer_id', 'name', name='uq_sites_customer_name')
    )
    op.create_index(op.f('ix_sites_created_at'), 'sites', ['created_at'], unique=False)
    op.create_index(op.f('ix_sites_created_by'), 'sites', ['created_by'], unique=False)
    op.create_index(op.f('ix_sites_customer_id'), 'sites', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sites_is_deleted'), 'sites', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_index(op.f('ix_sites_organisation_id'), 'sites', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_sites_source_kind'), 'sites', ['source_kind'], unique=False)
    op.create_index(op.f('ix_sites_status'), 'sites', ['status'], unique=False)
    op.create_index(op.f('ix_sites_updated_at'), 'sites', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sites_updated_by'), 'sites', ['updated_by'], unique=False)
    op.create_table('availability_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recurrence_rule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_periods_created_at'), 'availability_periods', ['created_at'], unique=False)
    op.create_index(op.f('ix_availability_periods_created_by'), 'availability_periods', ['created_by'], unique=False)
    op.create_index(op.f('ix_availability_periods_employee_id'), 'availability_periods', ['employee_id'], unique=False)
    op.create_index(op.f('ix_availability_periods_ends_at'), 'availability_periods', ['ends_at'], unique=False)
    op.create_index(op.f('ix_availability_periods_is_deleted'), 'availability_periods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_availability_periods_organisation_id'), 'availability_periods', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_availability_periods_starts_at'), 'availability_periods', ['starts_at'], unique=False)
    op.create_index(op.f('ix_availability_periods_status'), 'availability_periods', ['status'], unique=False)
    op.create_index(op.f('ix_availability_periods_updated_at'), 'availability_periods', ['updated_at'], unique=False)
    op.create_index(op.f('ix_availability_periods_updated_by'), 'availability_periods', ['updated_by'], unique=False)
    op.create_table('company_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_data', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['company_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'policy_type', 'version', name='uq_company_policy_version')
    )
    op.create_index(op.f('ix_company_policies_created_at'), 'company_policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_policies_created_by'), 'company_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_company_policies_is_deleted'), 'company_policies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_policies_organisation_id'), 'company_policies', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_company_policies_policy_type'), 'company_policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_company_policies_status'), 'company_policies', ['status'], unique=False)
    op.create_index(op.f('ix_company_policies_supersedes_id'), 'company_policies', ['supersedes_id'], unique=False)
    op.create_index(op.f('ix_company_policies_updated_at'), 'company_policies', ['updated_at'], unique=False)
    op.create_index(op.f('ix_company_policies_updated_by'), 'company_policies', ['updated_by'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(customer_id IS NOT NULL AND site_id IS NULL) OR (customer_id IS NULL AND site_id IS NOT NULL)', name='ck_contact_one_owner'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_created_by'), 'contacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_contacts_customer_id'), 'contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contacts_is_deleted'), 'contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contacts_organisation_id'), 'contacts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_contacts_site_id'), 'contacts', ['site_id'], unique=False)
    op.create_index(op.f('ix_contacts_updated_at'), 'contacts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_contacts_updated_by'), 'contacts', ['updated_by'], unique=False)
    op.create_table('daily_activity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('report_key', sa.String(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['daily_activity_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'report_key', 'revision', name='uq_daily_report_revision')
    )
    op.create_index(op.f('ix_daily_activity_reports_organisation_id'), 'daily_activity_reports', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_report_date'), 'daily_activity_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_report_key'), 'daily_activity_reports', ['report_key'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_site_id'), 'daily_activity_reports', ['site_id'], unique=False)
    op.create_index(op.f('ix_daily_activity_reports_status'), 'daily_activity_reports', ['status'], unique=False)
    op.create_table('employee_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'qualification_id', name='uq_employee_qualification')
    )
    op.create_index(op.f('ix_employee_qualifications_employee_id'), 'employee_qualifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_qualifications_organisation_id'), 'employee_qualifications', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_employee_qualifications_qualification_id'), 'employee_qualifications', ['qualification_id'], unique=False)
    op.create_index(op.f('ix_employee_qualifications_status'), 'employee_qualifications', ['status'], unique=False)
    op.create_table('evidence_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retention_status', sa.String(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence_attachments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_evidence_attachments_content_hash'), 'evidence_attachments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_attachments_media_type'), 'evidence_attachments', ['media_type'], unique=False)
    op.create_index(op.f('ix_evidence_attachments_organisation_id'), 'evidence_attachments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_evidence_attachments_retention_status'), 'evidence_attachments', ['retention_status'], unique=False)
    op.create_index(op.f('ix_evidence_attachments_status'), 'evidence_attachments', ['status'], unique=False)
    op.create_table('leave_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_periods_created_at'), 'leave_periods', ['created_at'], unique=False)
    op.create_index(op.f('ix_leave_periods_created_by'), 'leave_periods', ['created_by'], unique=False)
    op.create_index(op.f('ix_leave_periods_employee_id'), 'leave_periods', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_periods_ends_at'), 'leave_periods', ['ends_at'], unique=False)
    op.create_index(op.f('ix_leave_periods_is_deleted'), 'leave_periods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_periods_leave_type'), 'leave_periods', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leave_periods_organisation_id'), 'leave_periods', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_leave_periods_starts_at'), 'leave_periods', ['starts_at'], unique=False)
    op.create_index(op.f('ix_leave_periods_status'), 'leave_periods', ['status'], unique=False)
    op.create_index(op.f('ix_leave_periods_updated_at'), 'leave_periods', ['updated_at'], unique=False)
    op.create_index(op.f('ix_leave_periods_updated_by'), 'leave_periods', ['updated_by'], unique=False)
    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('licence_type', sa.String(), nullable=False),
    sa.Column('licence_identifier', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'licence_identifier', name='uq_licence_identifier')
    )
    op.create_index(op.f('ix_licences_created_at'), 'licences', ['created_at'], unique=False)
    op.create_index(op.f('ix_licences_created_by'), 'licences', ['created_by'], unique=False)
    op.create_index(op.f('ix_licences_employee_id'), 'licences', ['employee_id'], unique=False)
    op.create_index(op.f('ix_licences_expires_at'), 'licences', ['expires_at'], unique=False)
    op.create_index(op.f('ix_licences_is_deleted'), 'licences', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_licences_licence_identifier'), 'licences', ['licence_identifier'], unique=False)
    op.create_index(op.f('ix_licences_licence_type'), 'licences', ['licence_type'], unique=False)
    op.create_index(op.f('ix_licences_organisation_id'), 'licences', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_licences_status'), 'licences', ['status'], unique=False)
    op.create_index(op.f('ix_licences_updated_at'), 'licences', ['updated_at'], unique=False)
    op.create_index(op.f('ix_licences_updated_by'), 'licences', ['updated_by'], unique=False)
    op.create_table('patrol_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('route_description', sa.Text(), nullable=True),
    sa.Column('required_employees', sa.Integer(), nullable=False),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['patrol_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_templates_created_at'), 'patrol_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_patrol_templates_created_by'), 'patrol_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_patrol_templates_is_deleted'), 'patrol_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patrol_templates_organisation_id'), 'patrol_templates', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_patrol_templates_site_id'), 'patrol_templates', ['site_id'], unique=False)
    op.create_index(op.f('ix_patrol_templates_status'), 'patrol_templates', ['status'], unique=False)
    op.create_index(op.f('ix_patrol_templates_updated_at'), 'patrol_templates', ['updated_at'], unique=False)
    op.create_index(op.f('ix_patrol_templates_updated_by'), 'patrol_templates', ['updated_by'], unique=False)
    op.create_table('post_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_orders_category'), 'post_orders', ['category'], unique=False)
    op.create_index(op.f('ix_post_orders_created_at'), 'post_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_orders_created_by'), 'post_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_post_orders_is_deleted'), 'post_orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_post_orders_organisation_id'), 'post_orders', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_post_orders_site_id'), 'post_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_post_orders_status'), 'post_orders', ['status'], unique=False)
    op.create_index(op.f('ix_post_orders_updated_at'), 'post_orders', ['updated_at'], unique=False)
    op.create_index(op.f('ix_post_orders_updated_by'), 'post_orders', ['updated_by'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amendment_of_id', sa.Integer(), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['amendment_of_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_created_at'), 'shifts', ['created_at'], unique=False)
    op.create_index(op.f('ix_shifts_created_by'), 'shifts', ['created_by'], unique=False)
    op.create_index(op.f('ix_shifts_ends_at'), 'shifts', ['ends_at'], unique=False)
    op.create_index(op.f('ix_shifts_is_deleted'), 'shifts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shifts_organisation_id'), 'shifts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_shifts_site_id'), 'shifts', ['site_id'], unique=False)
    op.create_index(op.f('ix_shifts_starts_at'), 'shifts', ['starts_at'], unique=False)
    op.create_index(op.f('ix_shifts_status'), 'shifts', ['status'], unique=False)
    op.create_index(op.f('ix_shifts_updated_at'), 'shifts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shifts_updated_by'), 'shifts', ['updated_by'], unique=False)
    op.create_table('site_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_label', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['site_assets.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'site_id', 'asset_identifier', name='uq_site_asset_identifier')
    )
    op.create_index(op.f('ix_site_assets_asset_identifier'), 'site_assets', ['asset_identifier'], unique=False)
    op.create_index(op.f('ix_site_assets_asset_type'), 'site_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_site_assets_created_at'), 'site_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_site_assets_created_by'), 'site_assets', ['created_by'], unique=False)
    op.create_index(op.f('ix_site_assets_is_deleted'), 'site_assets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_site_assets_organisation_id'), 'site_assets', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_site_assets_parent_asset_id'), 'site_assets', ['parent_asset_id'], unique=False)
    op.create_index(op.f('ix_site_assets_site_id'), 'site_assets', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_assets_status'), 'site_assets', ['status'], unique=False)
    op.create_index(op.f('ix_site_assets_updated_at'), 'site_assets', ['updated_at'], unique=False)
    op.create_index(op.f('ix_site_assets_updated_by'), 'site_assets', ['updated_by'], unique=False)
    op.create_table('evidence_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_attachment_id', sa.Integer(), nullable=False),
    sa.Column('domain_object_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('linked_by_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_object_id'], ['domain_objects.id'], ),
    sa.ForeignKeyConstraint(['evidence_attachment_id'], ['evidence_attachments.id'], ),
    sa.ForeignKeyConstraint(['linked_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_attachment_id', 'domain_object_id', name='uq_evidence_domain_link')
    )
    op.create_index(op.f('ix_evidence_links_domain_object_id'), 'evidence_links', ['domain_object_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_evidence_attachment_id'), 'evidence_links', ['evidence_attachment_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_organisation_id'), 'evidence_links', ['organisation_id'], unique=False)
    op.create_table('operational_event_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('operational_event_id', sa.Integer(), nullable=False),
    sa.Column('domain_object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_object_id'], ['domain_objects.id'], ),
    sa.ForeignKeyConstraint(['operational_event_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operational_event_id', 'domain_object_id', name='uq_event_subject')
    )
    op.create_index(op.f('ix_operational_event_subjects_domain_object_id'), 'operational_event_subjects', ['domain_object_id'], unique=False)
    op.create_index(op.f('ix_operational_event_subjects_operational_event_id'), 'operational_event_subjects', ['operational_event_id'], unique=False)
    op.create_index(op.f('ix_operational_event_subjects_organisation_id'), 'operational_event_subjects', ['organisation_id'], unique=False)
    op.create_table('post_order_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('post_order_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['post_order_id'], ['post_orders.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['post_order_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_order_id', 'version', name='uq_post_order_version')
    )
    op.create_index(op.f('ix_post_order_versions_organisation_id'), 'post_order_versions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_post_order_versions_post_order_id'), 'post_order_versions', ['post_order_id'], unique=False)
    op.create_index(op.f('ix_post_order_versions_status'), 'post_order_versions', ['status'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(employee_id IS NOT NULL AND team_id IS NULL) OR (employee_id IS NULL AND team_id IS NOT NULL)', name='ck_shift_assignment_one_target'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_assignments_created_at'), 'shift_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shift_assignments_created_by'), 'shift_assignments', ['created_by'], unique=False)
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_is_deleted'), 'shift_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shift_assignments_organisation_id'), 'shift_assignments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_shift_id'), 'shift_assignments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_status'), 'shift_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_shift_assignments_team_id'), 'shift_assignments', ['team_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_updated_at'), 'shift_assignments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shift_assignments_updated_by'), 'shift_assignments', ['updated_by'], unique=False)
    op.create_table('post_order_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('post_order_version_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledgement_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['post_order_version_id'], ['post_order_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_order_version_id', 'employee_id', name='uq_post_order_ack_employee')
    )
    op.create_index(op.f('ix_post_order_acknowledgements_employee_id'), 'post_order_acknowledgements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_post_order_acknowledgements_organisation_id'), 'post_order_acknowledgements', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_post_order_acknowledgements_post_order_version_id'), 'post_order_acknowledgements', ['post_order_version_id'], unique=False)
    op.create_table('checkpoint_verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('patrol_occurrence_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['patrol_occurrence_id'], ['patrols.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoint_verification_events_checkpoint_id'), 'checkpoint_verification_events', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_employee_id'), 'checkpoint_verification_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_occurred_at'), 'checkpoint_verification_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_organisation_id'), 'checkpoint_verification_events', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_patrol_occurrence_id'), 'checkpoint_verification_events', ['patrol_occurrence_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_result'), 'checkpoint_verification_events', ['result'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_shift_id'), 'checkpoint_verification_events', ['shift_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_source_kind'), 'checkpoint_verification_events', ['source_kind'], unique=False)
    op.create_index(op.f('ix_checkpoint_verification_events_verification_method'), 'checkpoint_verification_events', ['verification_method'], unique=False)
    op.create_table('operational_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('domain_object_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('acknowledged_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['domain_object_id'], ['domain_objects.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_alerts_created_at'), 'operational_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_operational_alerts_created_by'), 'operational_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_operational_alerts_domain_object_id'), 'operational_alerts', ['domain_object_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_incident_id'), 'operational_alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_is_deleted'), 'operational_alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_operational_alerts_organisation_id'), 'operational_alerts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_severity'), 'operational_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_operational_alerts_status'), 'operational_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_operational_alerts_updated_at'), 'operational_alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_operational_alerts_updated_by'), 'operational_alerts', ['updated_by'], unique=False)
    op.create_table('patrol_template_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('patrol_template_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['patrol_template_id'], ['patrol_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patrol_template_id', 'checkpoint_id', name='uq_template_checkpoint'),
    sa.UniqueConstraint('patrol_template_id', 'sequence', name='uq_template_checkpoint_sequence')
    )
    op.create_index(op.f('ix_patrol_template_checkpoints_checkpoint_id'), 'patrol_template_checkpoints', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_patrol_template_checkpoints_organisation_id'), 'patrol_template_checkpoints', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_patrol_template_checkpoints_patrol_template_id'), 'patrol_template_checkpoints', ['patrol_template_id'], unique=False)
    op.add_column('alerts', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('patrol_occurrence_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('source_kind', sa.String(), nullable=False, server_default='legacy_alert'))
    op.add_column('alerts', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('record_version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_alerts_patrol_occurrence_id'), 'alerts', ['patrol_occurrence_id'], unique=False)
    op.create_index(op.f('ix_alerts_site_id'), 'alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_alerts_source_id'), 'alerts', ['source_id'], unique=False)
    op.create_index(op.f('ix_alerts_source_kind'), 'alerts', ['source_kind'], unique=False)
    op.create_foreign_key('fk_alerts_patrol_occurrence', 'alerts', 'patrols', ['patrol_occurrence_id'], ['id'])
    op.create_foreign_key('fk_alerts_site', 'alerts', 'sites', ['site_id'], ['id'])
    op.add_column('audit_logs', sa.Column('domain_object_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_employee_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('event_kind', sa.String(), nullable=False, server_default='audit'))
    op.add_column('audit_logs', sa.Column('event_metadata', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('visibility', sa.String(), nullable=False, server_default='restricted'))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('correction_of_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_actor_employee_id'), 'audit_logs', ['actor_employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correction_of_id'), 'audit_logs', ['correction_of_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_domain_object_id'), 'audit_logs', ['domain_object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_kind'), 'audit_logs', ['event_kind'], unique=False)
    op.create_index(op.f('ix_audit_logs_visibility'), 'audit_logs', ['visibility'], unique=False)
    op.create_foreign_key('fk_audit_logs_actor_employee', 'audit_logs', 'employees', ['actor_employee_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_correction', 'audit_logs', 'audit_logs', ['correction_of_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_domain_object', 'audit_logs', 'domain_objects', ['domain_object_id'], ['id'])
    op.add_column('checkpoints', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_checkpoints_site_id'), 'checkpoints', ['site_id'], unique=False)
    op.create_foreign_key('fk_checkpoints_site', 'checkpoints', 'sites', ['site_id'], ['id'])
    op.add_column('customers', sa.Column('commercial_metadata', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('domain_object_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('channel', sa.String(), nullable=False, server_default='in_app'))
    op.add_column('notifications', sa.Column('delivery_status', sa.String(), nullable=False, server_default='queued'))
    op.add_column('notifications', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('failed_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('failure_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_delivered_at'), 'notifications', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_notifications_delivery_status'), 'notifications', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_notifications_domain_object_id'), 'notifications', ['domain_object_id'], unique=False)
    op.create_index(op.f('ix_notifications_failed_at'), 'notifications', ['failed_at'], unique=False)
    op.create_foreign_key('fk_notifications_domain_object', 'notifications', 'domain_objects', ['domain_object_id'], ['id'])
    op.add_column('patrols', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('patrols', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('patrols', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.add_column('patrols', sa.Column('lifecycle_status', sa.String(), nullable=False, server_default='scheduled'))
    op.add_column('patrols', sa.Column('template_snapshot', sa.JSON(), nullable=True))
    op.add_column('patrols', sa.Column('amendment_of_id', sa.Integer(), nullable=True))
    op.add_column('patrols', sa.Column('record_version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_patrols_amendment_of_id'), 'patrols', ['amendment_of_id'], unique=False)
    op.create_index(op.f('ix_patrols_lifecycle_status'), 'patrols', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_patrols_shift_id'), 'patrols', ['shift_id'], unique=False)
    op.create_index(op.f('ix_patrols_site_id'), 'patrols', ['site_id'], unique=False)
    op.create_index(op.f('ix_patrols_template_id'), 'patrols', ['template_id'], unique=False)
    op.create_foreign_key('fk_patrols_site', 'patrols', 'sites', ['site_id'], ['id'])
    op.create_foreign_key('fk_patrols_amendment', 'patrols', 'patrols', ['amendment_of_id'], ['id'])
    op.create_foreign_key('fk_patrols_shift', 'patrols', 'shifts', ['shift_id'], ['id'])
    op.create_foreign_key('fk_patrols_template', 'patrols', 'patrol_templates', ['template_id'], ['id'])

    # Compatibility backfills. Existing rows remain in place; canonical rows
    # retain their source so a downgrade can distinguish migrated history from
    # new Phase 1 records.
    bind = op.get_bind()
    bind.execute(sa.text("""
        INSERT INTO employees (
            organisation_id, user_id, employee_identifier, display_name,
            employment_role, status, source_kind, created_at, updated_at,
            created_by, updated_by, is_deleted
        )
        SELECT organisation_id, id, staff_identifier,
               COALESCE(full_name, email),
               CASE WHEN role IN ('officer', 'employee') THEN 'security_officer' ELSE role END,
               CASE WHEN is_active THEN 'active' ELSE 'inactive' END,
               'legacy_user', created_at, updated_at, created_by, updated_by, is_deleted
        FROM users
    """))
    bind.execute(sa.text("""
        INSERT INTO sites (
            organisation_id, customer_id, name, address, timezone,
            staffing_requirement, status, source_kind, created_at, updated_at,
            created_by, updated_by, is_deleted
        )
        SELECT c.organisation_id, c.id, c.name || ' Primary Site',
               COALESCE(c.address, 'Address pending confirmation'),
               COALESCE(o.timezone, 'UTC'), 1,
               CASE WHEN c.is_deleted THEN 'archived' ELSE 'active' END,
               'legacy_customer_address', c.created_at, c.updated_at,
               c.created_by, c.updated_by, c.is_deleted
        FROM customers c
        JOIN organisations o ON o.id = c.organisation_id
    """))
    if bind.dialect.name == 'postgresql':
        bind.execute(sa.text(
            "SELECT setval(pg_get_serial_sequence('alerts', 'id'), "
            "COALESCE((SELECT MAX(id) FROM alerts), 0) + 1, false)"
        ))
    bind.execute(sa.text("""
        INSERT INTO alerts (
            title, description, severity, status, reported_at, reported_by,
            organisation_id, created_at, updated_at, is_deleted, category,
            source_kind, source_id, record_version
        )
        SELECT 'Legacy incident ' || CAST(i.id AS TEXT), i.description,
               i.severity, 'open', i.timestamp, i.user_id,
               i.organisation_id, i.timestamp, i.timestamp, false, 'security',
               'legacy_incident', CAST(i.id AS TEXT), 1
        FROM incidents i
    """))

    registry_sources = (
        ('organisation', 'organisations', 'organisation', 'organisations'),
        ('customer', 'customers', 'customer', 'customers'),
        ('site', 'sites', 'site', 'sites'),
        ('employee', 'employees', 'employee', 'employees'),
        ('team', 'teams', 'team', 'teams'),
        ('patrol_occurrence', 'patrols', 'patrol_occurrence', 'patrol_occurrences'),
        ('checkpoint', 'checkpoints', 'site', 'checkpoints'),
        ('incident', 'alerts', 'incident', 'incidents'),
        ('notification', 'notifications', 'notification', 'notifications'),
    )
    for object_type, table_name, root_type, service in registry_sources:
        organisation_expression = 'id' if table_name == 'organisations' else 'organisation_id'
        bind.execute(sa.text(
            f"INSERT INTO domain_objects ("
            f"organisation_id, object_type, object_id, aggregate_root_type, "
            f"aggregate_root_id, owning_service, created_at) "
            f"SELECT {organisation_expression}, :object_type, id, :root_type, id, :service, "
            f"CURRENT_TIMESTAMP FROM {table_name}"
        ), {'object_type': object_type, 'root_type': root_type, 'service': service})

    bind.execute(sa.text("""
        INSERT INTO checkpoint_verification_events (
            organisation_id, checkpoint_id, patrol_occurrence_id, employee_id,
            occurred_at, verification_method, result, latitude, longitude, source_kind
        )
        SELECT c.organisation_id, c.id, c.patrol_id, e.id,
               COALESCE(c.verified_at, c.updated_at), 'legacy_code', 'accepted',
               c.latitude, c.longitude, 'legacy_checkpoint_state'
        FROM checkpoints c
        JOIN employees e ON e.user_id = c.verified_by
        WHERE c.status = 'verified'
    """))

    # Remove migration-only defaults so runtime values remain explicit.
    for table_name, column_name in (
        ('alerts', 'source_kind'), ('alerts', 'record_version'),
        ('audit_logs', 'event_kind'), ('audit_logs', 'visibility'),
        ('notifications', 'channel'), ('notifications', 'delivery_status'),
        ('patrols', 'lifecycle_status'), ('patrols', 'record_version'),
    ):
        op.alter_column(table_name, column_name, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    guarded_tables = (
        'company_policies', 'contacts', 'daily_activity_reports', 'employee_qualifications',
        'evidence_attachments', 'evidence_links', 'leave_periods', 'licences',
        'operational_alerts', 'operational_event_subjects', 'patrol_template_checkpoints',
        'patrol_templates', 'post_order_acknowledgements', 'post_order_versions',
        'post_orders', 'qualifications', 'shift_assignments', 'shifts', 'site_assets',
    )
    for table_name in guarded_tables:
        if bind.execute(sa.text(f'SELECT COUNT(*) FROM {table_name}')).scalar_one():
            raise RuntimeError(
                f'Cannot downgrade Phase 1 while {table_name} contains canonical records'
            )
    if bind.execute(sa.text(
        "SELECT COUNT(*) FROM employees WHERE source_kind <> 'legacy_user'"
    )).scalar_one():
        raise RuntimeError('Cannot downgrade Phase 1 while native employees exist')
    if bind.execute(sa.text(
        "SELECT COUNT(*) FROM sites WHERE source_kind <> 'legacy_customer_address'"
    )).scalar_one():
        raise RuntimeError('Cannot downgrade Phase 1 while native sites exist')
    if bind.execute(sa.text(
        "SELECT COUNT(*) FROM checkpoint_verification_events "
        "WHERE source_kind <> 'legacy_checkpoint_state'"
    )).scalar_one():
        raise RuntimeError('Cannot downgrade Phase 1 while native checkpoint events exist')
    bind.execute(sa.text("DELETE FROM alerts WHERE source_kind = 'legacy_incident'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_patrols_template', 'patrols', type_='foreignkey')
    op.drop_constraint('fk_patrols_shift', 'patrols', type_='foreignkey')
    op.drop_constraint('fk_patrols_amendment', 'patrols', type_='foreignkey')
    op.drop_constraint('fk_patrols_site', 'patrols', type_='foreignkey')
    op.drop_index(op.f('ix_patrols_template_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_site_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_shift_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_lifecycle_status'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_amendment_of_id'), table_name='patrols')
    op.drop_column('patrols', 'record_version')
    op.drop_column('patrols', 'amendment_of_id')
    op.drop_column('patrols', 'template_snapshot')
    op.drop_column('patrols', 'lifecycle_status')
    op.drop_column('patrols', 'shift_id')
    op.drop_column('patrols', 'template_id')
    op.drop_column('patrols', 'site_id')
    op.drop_constraint('fk_notifications_domain_object', 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_failed_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_domain_object_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_delivery_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_delivered_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_column('notifications', 'failure_code')
    op.drop_column('notifications', 'failed_at')
    op.drop_column('notifications', 'delivered_at')
    op.drop_column('notifications', 'delivery_status')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'domain_object_id')
    op.drop_column('customers', 'commercial_metadata')
    op.drop_constraint('fk_checkpoints_site', 'checkpoints', type_='foreignkey')
    op.drop_index(op.f('ix_checkpoints_site_id'), table_name='checkpoints')
    op.drop_column('checkpoints', 'site_id')
    op.drop_constraint('fk_audit_logs_domain_object', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_correction', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_actor_employee', 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_visibility'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_kind'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_domain_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correction_of_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_employee_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'correction_of_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'visibility')
    op.drop_column('audit_logs', 'event_metadata')
    op.drop_column('audit_logs', 'event_kind')
    op.drop_column('audit_logs', 'actor_employee_id')
    op.drop_column('audit_logs', 'domain_object_id')
    op.drop_constraint('fk_alerts_site', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_patrol_occurrence', 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_source_kind'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_site_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patrol_occurrence_id'), table_name='alerts')
    op.drop_column('alerts', 'record_version')
    op.drop_column('alerts', 'source_id')
    op.drop_column('alerts', 'source_kind')
    op.drop_column('alerts', 'patrol_occurrence_id')
    op.drop_column('alerts', 'site_id')
    op.drop_index(op.f('ix_patrol_template_checkpoints_patrol_template_id'), table_name='patrol_template_checkpoints')
    op.drop_index(op.f('ix_patrol_template_checkpoints_organisation_id'), table_name='patrol_template_checkpoints')
    op.drop_index(op.f('ix_patrol_template_checkpoints_checkpoint_id'), table_name='patrol_template_checkpoints')
    op.drop_table('patrol_template_checkpoints')
    op.drop_index(op.f('ix_operational_alerts_updated_by'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_updated_at'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_status'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_severity'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_organisation_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_is_deleted'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_incident_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_domain_object_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_created_by'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_created_at'), table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index(op.f('ix_checkpoint_verification_events_verification_method'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_source_kind'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_shift_id'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_result'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_patrol_occurrence_id'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_organisation_id'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_occurred_at'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_employee_id'), table_name='checkpoint_verification_events')
    op.drop_index(op.f('ix_checkpoint_verification_events_checkpoint_id'), table_name='checkpoint_verification_events')
    op.drop_table('checkpoint_verification_events')
    op.drop_index(op.f('ix_post_order_acknowledgements_post_order_version_id'), table_name='post_order_acknowledgements')
    op.drop_index(op.f('ix_post_order_acknowledgements_organisation_id'), table_name='post_order_acknowledgements')
    op.drop_index(op.f('ix_post_order_acknowledgements_employee_id'), table_name='post_order_acknowledgements')
    op.drop_table('post_order_acknowledgements')
    op.drop_index(op.f('ix_shift_assignments_updated_by'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_updated_at'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_team_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_status'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_shift_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_organisation_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_is_deleted'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_created_by'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_created_at'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_post_order_versions_status'), table_name='post_order_versions')
    op.drop_index(op.f('ix_post_order_versions_post_order_id'), table_name='post_order_versions')
    op.drop_index(op.f('ix_post_order_versions_organisation_id'), table_name='post_order_versions')
    op.drop_table('post_order_versions')
    op.drop_index(op.f('ix_operational_event_subjects_organisation_id'), table_name='operational_event_subjects')
    op.drop_index(op.f('ix_operational_event_subjects_operational_event_id'), table_name='operational_event_subjects')
    op.drop_index(op.f('ix_operational_event_subjects_domain_object_id'), table_name='operational_event_subjects')
    op.drop_table('operational_event_subjects')
    op.drop_index(op.f('ix_evidence_links_organisation_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_evidence_attachment_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_domain_object_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_site_assets_updated_by'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_updated_at'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_status'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_site_id'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_parent_asset_id'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_organisation_id'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_is_deleted'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_created_by'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_created_at'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_asset_type'), table_name='site_assets')
    op.drop_index(op.f('ix_site_assets_asset_identifier'), table_name='site_assets')
    op.drop_table('site_assets')
    op.drop_index(op.f('ix_shifts_updated_by'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_updated_at'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_status'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_starts_at'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_site_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_organisation_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_is_deleted'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_ends_at'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_created_by'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_created_at'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_post_orders_updated_by'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_updated_at'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_status'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_site_id'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_organisation_id'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_is_deleted'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_created_by'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_created_at'), table_name='post_orders')
    op.drop_index(op.f('ix_post_orders_category'), table_name='post_orders')
    op.drop_table('post_orders')
    op.drop_index(op.f('ix_patrol_templates_updated_by'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_updated_at'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_status'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_site_id'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_organisation_id'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_is_deleted'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_created_by'), table_name='patrol_templates')
    op.drop_index(op.f('ix_patrol_templates_created_at'), table_name='patrol_templates')
    op.drop_table('patrol_templates')
    op.drop_index(op.f('ix_licences_updated_by'), table_name='licences')
    op.drop_index(op.f('ix_licences_updated_at'), table_name='licences')
    op.drop_index(op.f('ix_licences_status'), table_name='licences')
    op.drop_index(op.f('ix_licences_organisation_id'), table_name='licences')
    op.drop_index(op.f('ix_licences_licence_type'), table_name='licences')
    op.drop_index(op.f('ix_licences_licence_identifier'), table_name='licences')
    op.drop_index(op.f('ix_licences_is_deleted'), table_name='licences')
    op.drop_index(op.f('ix_licences_expires_at'), table_name='licences')
    op.drop_index(op.f('ix_licences_employee_id'), table_name='licences')
    op.drop_index(op.f('ix_licences_created_by'), table_name='licences')
    op.drop_index(op.f('ix_licences_created_at'), table_name='licences')
    op.drop_table('licences')
    op.drop_index(op.f('ix_leave_periods_updated_by'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_updated_at'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_status'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_starts_at'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_organisation_id'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_leave_type'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_is_deleted'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_ends_at'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_employee_id'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_created_by'), table_name='leave_periods')
    op.drop_index(op.f('ix_leave_periods_created_at'), table_name='leave_periods')
    op.drop_table('leave_periods')
    op.drop_index(op.f('ix_evidence_attachments_status'), table_name='evidence_attachments')
    op.drop_index(op.f('ix_evidence_attachments_retention_status'), table_name='evidence_attachments')
    op.drop_index(op.f('ix_evidence_attachments_organisation_id'), table_name='evidence_attachments')
    op.drop_index(op.f('ix_evidence_attachments_media_type'), table_name='evidence_attachments')
    op.drop_index(op.f('ix_evidence_attachments_content_hash'), table_name='evidence_attachments')
    op.drop_table('evidence_attachments')
    op.drop_index(op.f('ix_employee_qualifications_status'), table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_qualification_id'), table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_organisation_id'), table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_employee_id'), table_name='employee_qualifications')
    op.drop_table('employee_qualifications')
    op.drop_index(op.f('ix_daily_activity_reports_status'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_site_id'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_report_key'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_report_date'), table_name='daily_activity_reports')
    op.drop_index(op.f('ix_daily_activity_reports_organisation_id'), table_name='daily_activity_reports')
    op.drop_table('daily_activity_reports')
    op.drop_index(op.f('ix_contacts_updated_by'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_updated_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_site_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organisation_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_deleted'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_customer_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_by'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_policies_updated_by'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_updated_at'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_supersedes_id'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_status'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_policy_type'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_organisation_id'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_is_deleted'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_created_by'), table_name='company_policies')
    op.drop_index(op.f('ix_company_policies_created_at'), table_name='company_policies')
    op.drop_table('company_policies')
    op.drop_index(op.f('ix_availability_periods_updated_by'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_updated_at'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_status'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_starts_at'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_organisation_id'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_is_deleted'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_ends_at'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_employee_id'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_created_by'), table_name='availability_periods')
    op.drop_index(op.f('ix_availability_periods_created_at'), table_name='availability_periods')
    op.drop_table('availability_periods')
    op.drop_index(op.f('ix_sites_updated_by'), table_name='sites')
    op.drop_index(op.f('ix_sites_updated_at'), table_name='sites')
    op.drop_index(op.f('ix_sites_status'), table_name='sites')
    op.drop_index(op.f('ix_sites_source_kind'), table_name='sites')
    op.drop_index(op.f('ix_sites_organisation_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_is_deleted'), table_name='sites')
    op.drop_index(op.f('ix_sites_customer_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_created_by'), table_name='sites')
    op.drop_index(op.f('ix_sites_created_at'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_updated_by'), table_name='employees')
    op.drop_index(op.f('ix_employees_updated_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_source_kind'), table_name='employees')
    op.drop_index(op.f('ix_employees_organisation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_role'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_identifier'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_by'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_qualifications_updated_by'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_updated_at'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_status'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_organisation_id'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_is_deleted'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_created_by'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_created_at'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_code'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_domain_objects_retired_at'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_organisation_id'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_object_type'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_object_id'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_created_at'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_aggregate_root_type'), table_name='domain_objects')
    op.drop_index(op.f('ix_domain_objects_aggregate_root_id'), table_name='domain_objects')
    op.drop_table('domain_objects')
    # ### end Alembic commands ###
